version: '3.8'

services:
  web:
    build: .
    container_name: vulnerable_web
    user: root  # Roda como root
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "echo '🛡️  Servidor Web Vulnerable iniciado, Invada Se for capaz!!!'; apache2-foreground"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: vulnerable_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnerable_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  db_data:

